---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: flask-demo
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: flask-demo-image-repo
  filterTags:
    pattern: '^dev\.(?P<timestamp>.*)Z$'
    extract: '$timestamp'
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: flask-demo
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: k8s-repo
  update:
    path: ./apps/flask-demo
    strategy: Setters